name: 1Password Load Secrets Action
description: Loads secrets into your GitHub runner from 1Password
author: KamaranL
branding:
  icon: lock
  color: blue

inputs:
  export-env:
    description: Export secrets as environment variables
    default: 'true'
  unset-previous:
    description: Unset previously loaded secrets stored in environment variables
    default: 'false'

runs:
  using: node20
  main: dist/index.js

